apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: interview-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: jaishankar7655/school_managemt:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          command:
            - sh
            - -c
            - |
              until nc -z $MYSQL_HOST $MYSQL_PORT; do
                echo "Waiting for MySQL..."
                sleep 3
              done
              python manage.py migrate
              python manage.py runserver 0.0.0.0:8000

