apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: school-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: jaishankar7655/django_school_app:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: SECRET_KEY

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: school-secret
                  key: MYSQL_USER

            - name: MYSQL_HOST
              value: mysql-service

            - name: MYSQL_PORT
              value: "3306"
