kind: Service
apiVersion: v1

metadata:
  name: django-service
  namespace: school-app

spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer