apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: interview-namespace
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    events { worker_connections 1024; }
    http {
        server {
            listen 80;
            location / {
                proxy_pass http://django-service:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            location /static/ {
                alias /static/;
            }
            location /media/ {
                alias /media/;
            }
        }
    }

