apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: interview-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: static-volume
              mountPath: /static
            - name: media-volume
              mountPath: /media
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
        - name: static-volume
          emptyDir: {}
        - name: media-volume
          emptyDir: {}

