apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: school-app
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://django-service:8000;
      }
    }

